### ISSUE TITLE
How to remove messages from the queue once received?

### ISSUE THREAD

**Issue by daveseff** [ozen/yosun#3]
Once my subscriber received a message from the queue, I need the message to be removed from the queue. 

What I am seeing is that the messages get acked and actioned by my subscriber, But they are accumulating on the queue. I may have potentially thousands of messages a day so How can I manage this?

**Comment by ozen** [comment]
As far as I remember, the producer must set the TTL for the messages. 

RabbitMQ: https://www.rabbitmq.com/ttl.html

In Kombu, the _publish_ method has _expiration_ parameter for this.
